### PR TITLE
Add license field to the table

### PR DESCRIPTION
**Pull request by dilarasoylu**
Making the license field visible in the table.

### CODE REVIEW

**Comment by percyliang** [comment]
Can you provide a screenshot?  Want to make sure it doesn't look too busy.

**Comment by dilarasoylu** [comment]
> Can you provide a screenshot? Want to make sure it doesn't look too busy.

**Comment by percyliang** [comment]
It doesn't seem like the screenshot uploaded?

**Comment by dilarasoylu** [comment]
> It doesn't seem like the screenshot uploaded?

Oops, sorry, updated now.

**Review by percyliang — APPROVED** [review]
Thanks!

**Pull request merged**
